[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cires21"
authors = [{name = "Cires21", email = "info@cires21.com"}]
dynamic = ["version", "description"]
